export const GET_PROGRESS_PENDING = 'GET_PROGRESS_PENDING';
export const GET_PROGRESS_FAILURE = 'GET_PROGRESS_FAILURE';
export const GET_PROGRESS_SUCCESS = 'GET_PROGRESS_SUCCESS';
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';